### PR TITLE
Boss rush command

### PR DESCRIPTION
**Pull request by PizzaCrust**

### CODE REVIEW

**Comment by GOKU-SA** [comment]
I would love if there was "clearallmissions" command, what it would do is basically have the bot attempt to clear all king kai missions, korin missions, supreme kai missions etc. Could you add that sometime?

**Comment by FlashChaser** [comment]
Hey can you work this and use the complete_area command instead? Just helps if bandai updates with a new bossrush so we don't have to add it in manually.

**Comment by GOKU-SA** [comment]
Yeah, works for me. But it's fine if you can't add my recommendation.

**Comment by PizzaCrust** [comment]
Yeah, this was just a quick solution to implement this. I'll implement it today

**Comment by PizzaCrust** [comment]
Im gonna resubmit this PR with complete_area

**Pull request closed without merging**
